spring.application.name=student-management-system
server.port=8080
spring.datasource.url=jdbc:postgresql://db.mbyerlcdabljvslpesyr.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=,w3ciJLPAdHz.9M
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update

# JWT Configuration
jwt.secret=StudentMgmtSecretKey2024SuperLongSecretKeyForSecurity!
jwt.expiration=86400000